//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchebPrakGIBDD_integ.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GIBDDEntities : DbContext
    {
        public GIBDDEntities()
            : base("name=GIBDDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<Avtomobil> Avtomobil { get; set; }
        public virtual DbSet<Code_Regiona> Code_Regiona { get; set; }
        public virtual DbSet<Cvet_Mashini> Cvet_Mashini { get; set; }
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<Mesto_raboti> Mesto_raboti { get; set; }
        public virtual DbSet<Privod> Privod { get; set; }
        public virtual DbSet<Shtrafi> Shtrafi { get; set; }
        public virtual DbSet<Statys_Shtrafa> Statys_Shtrafa { get; set; }
        public virtual DbSet<Statys_VY> Statys_VY { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tip_Dvigatelia> Tip_Dvigatelia { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Voditel> Voditel { get; set; }
        public virtual DbSet<Voditelskoe_ydostoverenie> Voditelskoe_ydostoverenie { get; set; }
        public virtual DbSet<VY_Istoria_Statysa> VY_Istoria_Statysa { get; set; }
    }
}
