//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchebPrakGIBDD_integ.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shtrafi
    {
        public int ID { get; set; }
        public int VY_ID { get; set; }
        public int Avtomobil_ID { get; set; }
        public int Statys_ID { get; set; }
        public string Symma { get; set; }
    
        public virtual Avtomobil Avtomobil { get; set; }
        public virtual Statys_Shtrafa Statys_Shtrafa { get; set; }
        public virtual Voditelskoe_ydostoverenie Voditelskoe_ydostoverenie { get; set; }
    }
}
