//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchebPrakGIBDD_integ.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voditel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voditel()
        {
            this.Voditelskoe_ydostoverenie = new HashSet<Voditelskoe_ydostoverenie>();
        }
    
        public int ID { get; set; }
        public string Imia { get; set; }
        public string Familia { get; set; }
        public string Vtoroe_Imia { get; set; }
        public int Seria_pasporta { get; set; }
        public int Nomer_Pasporta { get; set; }
        public int Adres_prop_ID { get; set; }
        public int Adres_proziv_ID { get; set; }
        public int Mesto_raboti_ID { get; set; }
        public string Telefon { get; set; }
        public string Pochta { get; set; }
        public string Foto { get; set; }
        public string Opisanie { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Adres Adres1 { get; set; }
        public virtual Mesto_raboti Mesto_raboti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voditelskoe_ydostoverenie> Voditelskoe_ydostoverenie { get; set; }
    }
}
